### ISSUE TITLE
Version 3.0 - Roadmap

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#464]
### Version 3 Roadmap

The 3rd version of this soap-client will:

* aim to get rid of many [known ext-soap annoyances](https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md).
* by focussing on [strictening the types](https://github.com/php-soap/.github/blob/main/PROJECTS.md#better-types) of the generated code.
* powered by the information [read from the WSDL file directly](https://github.com/php-soap/wsdl-reader).

Actions:

* [x] Parse all wsdl information into usable metadata. Done in [wsdl-reader](https://github.com/php-soap/wsdl-reader) - feel free to play around with it!
* [x] Add support for soap-engine v2 and the newly introduced wsdl-reader package
  * (handled by #463)
  * Added ability to specify missing XSD parts and preferred SOAP version (Done in https://github.com/phpro/soap-client/pull/481)
* [x] Improve duplicate type-checker logic in code generation. (see #https://github.com/phpro/soap-client/issues/446) 
* [x] Better support for simple types
  * (Fixes https://github.com/phpro/soap-client/issues/434, https://github.com/phpro/soap-client/issues/376)
  * [x] Testcase : validate protel webservice (enums, unions,  ...) are resolved as the TypeName. But should be infered from the type instead !
  * [x] (Fixed in https://github.com/phpro/soap-client/pull/482)
* [x] Add nullable types based on minOccurs and maxOccurs, isNil, ... + add support for XSD choice-type
  * (Fixes https://github.com/phpro/soap-client/issues/282, #436 ...)
  * (Done in https://github.com/phpro/soap-client/pull/463)
* [x] Make it possible to mark a property as nullable during code generation from getter / property point of view.
  * (Done in https://github.com/phpro/soap-client/pull/480)  
* [x] Add array types based on minOccurs and maxOccurs
  * (Fixes https://github.com/phpro/soap-client/issues/346, https://github.com/phpro/soap-client/issues/231, , https://github.com/phpro/soap-client/issues/344, ...)
  * (Done in https://github.com/phpro/soap-client/pull/463)
* [x] Support for inheritence to generated code: extends + abstract
  * (Fixes https://github.com/phpro/soap-client/issues/311, https://github.com/phpro/soap-client/issues/291, https://github.com/phpro/soap-client/issues/156, https://github.com/phpro/soap-client/issues/144, #372)
* [x] Add support for XSD enum types (to check if it is possible to use PHP enums in combination with ext-soap)
  * (Fixes #403, #340, #217, #172, ...)
* [x] Add support for XSD union types
* [x] Make sure no classes are generated for simple types. 
  * (See #467)
* [x] Add wsdl docs to the generated methods and properties' docblocks
  * (done in https://github.com/phpro/soap-client/pull/463)
* [x] Add support for simple types on method level
  * (Fixes #467)
* [x] Other Code generation improvements
  * [x] Better getter/setter name generation (see https://github.com/phpro/soap-client/pull/478)
* [x] Docs cleanup 

### Timeframe

Development happens when it happens... Currently it is going at about 1d per 2 months.
It's a lot of work, so there are a ways you can help out speeding up the process.
By [sponsoring the project](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md#sponsor), we can inject some more time into this project.
