### ISSUE TITLE
Version X - Encoding improvements

### ISSUE THREAD

**Issue by veewee** [phpro/soap-client#485]
### Feature Request

The most known issues happen at ext-soap encoding / decoding's.
Again, because these are limitations in PHP's SOAP implementation, it is not something we can deal with at this time.
In order to solve this, we would need to write a pure PHP encoding / decoding implementation - which is a lot of work.

In this issue, we'll list the known issues:

#### Summary

- [x] Lack of support for [namespaced (duplicate) type-names](https://github.com/phpro/soap-client/blob/master/docs/known-issues/ext-soap.md#duplicate-typenames)
- [x] Type converters
  - [x] Lack of built-in support for [encoding / decoding enums](https://github.com/phpro/soap-client/blob/master/docs/
known-issues/ext-soap.md#enumerations)
  - [x] Unkown element context when converting to xml from inside a `typemap` (https://github.com/phpro/soap-client/discussions/501)
  - [x] Make it possible to provide a type converter for the `any` xsd type (https://github.com/php-soap/ext-soap-engine/issues/17)
- [x] A property with a hyphen or other non-accepted property character in the name (#477)
- [x] An easier way to deal with CDATA
  - [x] (https://github.com/php-soap/ext-soap-engine/issues/19)
- [x] Improve support for special array types like soapenc:array, apache:map, ... See:
  - [x] (https://github.com/phpro/soap-client/issues/504#issuecomment-1980883564 and https://github.com/phpro/soap-client/issues/504#issuecomment-1981162602)
- [x] hydrate nested inherited private props (https://github.com/phpro/soap-client/issues/513, https://github.com/phpro/soap-client/issues/523)
- [x] Validate that nullable response types dont result in an unitialized property issue (https://github.com/phpro/soap-client/issues/515)

**Requested BC breaks** 
- [x] Code generation improvements
  - [x] Allow getters/Setters with underscores (https://github.com/phpro/soap-client/issues/502)

...

####  Timeframe

Development happens when it happens... 
By [sponsoring the project](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md#sponsor), we can inject some more time into this project.

## [Find out how you can help out](https://github.com/php-soap/.github/blob/main/HELPING_OUT.md) 💚

**Comment by veewee** [comment]
All of the above is included in 
https://github.com/phpro/soap-client/releases/tag/4.0.0-alpha1

Feel free to play around with it!
